name: plotly
channels:
  - defaults
dependencies:
  - jupyter=1.0
  - jupyterlab=3.5
  - matplotlib=3.6
  - numpy=1.23
  - pandas=1.5
  - pip
  - python=3.10
  - scikit-learn=1.2
  - scipy=1.10
  - pip:
    - plotly==5.13
